### ISSUE TITLE
Release tags and changelog

### ISSUE THREAD

**Issue by johnjohndoe** [xxv/android-lifecycle#4]
Can you please at **tags** via `git tag -a "v.0.9.0" -m "Added this and that"` and a `CHANGELOG.md` to the repository such as [this](https://github.com/johnjohndoe/TypedPreferences/blob/master/CHANGELOG.md).

**Comment by axd1967** [comment]
why not storing changes in the tags, and viewing the Tags/Releases pages (https://github.com/xxv/android-lifecycle/tags), as done e.g here: https://github.com/botherder/detekt/tags ?

**Comment by johnjohndoe** [comment]
This is a matter of taste. I prefer a plain text file such as `CHANGELOG.md` since it allows me to move the repository to any place while taking the changelog with me. GitHub release tags are nice but can only be used with this service.

**Comment by xxv** [comment]
I added a tag for the one version I've got now and will add more as more revisions get made. I'm not going to add a `CHANGELOG.md`, though, as that's what commit messages and/or tag messages are for.

**Comment by johnjohndoe** [comment]
Please also add the tag to the graphic.

**Comment by xxv** [comment]
I'm not sure I understand what you mean. The diagram has the text `v0.9.0` on it already.

**Comment by johnjohndoe** [comment]
Awesome! Sorry, I did not see it.

**Comment by axd1967** [comment]
exactly - a `CHANGELOG` document is just a duplicated effort; and carrying whatever around can be done far more efficiently by carrying e.g. a git bundle, then you have everything.

**Comment by johnjohndoe** [comment]
I consider a `CHANGELOG` a well-formed summary of the most important changes. It is - so to say - a textual description of the public interface for other developers. Commit messages contain much more detail and not all these information are of interest for "users".

**Comment by axd1967** [comment]
You are right - except that that changelog summary can be written in a tag.

but indeed, if there is a need to provide the info **to the end user** (and I do not refer to a developer, but e.g. a user consulting a website) , then some kind of file is needed.

if the intention is to present CHANGELOG info **to a developer**, the tag is one of the few places to store that info.

but agreed, the inconvenience is that the changelog info is not available without Git. but someone who cannot use Git will not be able to use the repository, so that's not a real issue.

**Comment by johnjohndoe** [comment]
Please do not mistake GitHub for Git. You can put the notes in:

* CHANGELOG.md
* Git tags
* GitHub release notes

Only the first and the second will go with the repository. The last one will stay at github.com.

**Comment by axd1967** [comment]
Ah yes, I didn't even think of GitHub - but that's indeed yet another factor :-)
